spring.application.name=gpt
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.servlet.multipart.max-file-size = 50MB
spring.servlet.multipart.max-request-size = 50MB
server.tomcat.max-swallow-size = 100MB
server.port=10020
# database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/gpt?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=admin123
# MyBatis-Plus
mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
mybatis-plus.type-aliases-package=com.scnu.gpt.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.id-type= auto
# log
logging.file.name=application.log
logging.file.path=./logs/app.log
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
# FastGPT API
api.fastgpt.url=http://localhost:3000/api/v1/chat/completions
api.fastgpt.key=fastgpt-qogLhVdbBzUikUDUESLszbAyktUeOld4Ea4zdcKcY2L5GCBgsOpPVJBu7f1GQl
# Dify API
